version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@1.0.0

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - hmpps/helm_lint:
          name: helm_lint
          env: "prod"
      - hmpps/build_docker:
          name: build_docker
          filters:
            branches:
              only: main
      - hmpps/deploy_env:
          name: deploy_prod
          env: "prod"
          slack_notification: true
          context: dps-toolkit
          requires:
            - helm_lint
            - build_docker
          filters:
            branches:
              only: main
