version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@3.11

executors:
  auditor:
    docker:
      - image: circleci/ruby:2-buster
    working_directory: ~/app

jobs:
  security_audit:
    executor: auditor
    steps:
      - checkout
      - restore_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}
      - run:
          name: "Install Dependencies"
          command: |
            gem install bundler
            bundle install --path=./.gem
      - save_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - ./.gem
      - run:
          name: Run security audit
          command: bundle exec bundle audit check --update

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - security_audit
      - hmpps/helm_lint:
          name: helm_lint
          env: "prod"
      - hmpps/build_docker:
          name: build_docker
          filters:
            branches:
              only: main
      - hmpps/deploy_env:
          name: deploy_prod
          env: "prod"
          slack_notification: true
          context:
            - hmpps-common-vars
            - dps-toolkit
          requires:
            - security_audit
            - helm_lint
            - build_docker
          filters:
            branches:
              only: main

  security:
    triggers:
      - schedule:
          cron: "42 3 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - security_audit
      - hmpps/trivy_latest_scan:
          context:
            - hmpps-common-vars
      - hmpps/veracode_pipeline_scan:
          context:
            - veracode-credentials
            - hmpps-common-vars
  security-weekly:
    triggers:
      - schedule:
          cron: "12 4 * * 1"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/veracode_policy_scan:
          context:
            - veracode-credentials
            - hmpps-common-vars
