version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@3.11
  ruby: circleci/ruby@1

executors:
  ruby:
    docker:
      - image: cimg/ruby:3.1-node
    working_directory: ~/app

jobs:
  tests:
    executor: ruby
    steps:
      - checkout
      - restore_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}
      - ruby/install-deps
      - save_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - ./.gem
      - ruby/rubocop-check:
          format: progress
          label: Inspecting with Rubocop
      - run:
          name: Run security audit
          command: bundle exec bundle audit check --update

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - tests
      - hmpps/helm_lint:
          name: helm_lint
          env: "prod"
      - hmpps/build_docker:
          name: build_docker
          filters:
            branches:
              only: main
      - hmpps/deploy_env:
          name: deploy_prod
          env: "prod"
          slack_notification: true
          context:
            - hmpps-common-vars
            - dps-toolkit
          requires:
            - tests
            - helm_lint
            - build_docker
          filters:
            branches:
              only: main

  security:
    triggers:
      - schedule:
          cron: "42 3 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/trivy_latest_scan:
          slack_channel: hmpps_tech_alerts_security
          context:
            - hmpps-common-vars
      - hmpps/veracode_pipeline_scan:
          slack_channel: hmpps_tech_alerts_security
          context:
            - veracode-credentials
            - hmpps-common-vars
  security-weekly:
    triggers:
      - schedule:
          cron: "12 4 * * 1"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/veracode_policy_scan:
          slack_channel: hmpps_tech_alerts_security
          context:
            - veracode-credentials
            - hmpps-common-vars
