---
# Values here are the same across all environments
generic-service:
  nameOverride: dps-monitor

  image:
    repository: quay.io/hmpps/dps-monitor
    tag: app_version  # override at deployment time
    port: 3030

  ingress:
    enabled: true
    tlsSecretName: dps-monitor-cert

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]
  namespace_secrets:
    dps-monitor:
      CIRCLE_CI_TOKEN: "CIRCLE_CI_TOKEN"

  allowlist:
    office: "217.33.148.210/32"
    mojvpn: "81.134.202.29/32"
    cloudplatform-live1-1: "35.178.209.113/32"
    cloudplatform-live1-2: "3.8.51.207/32"
    cloudplatform-live1-3: "35.177.252.54/32"
    quantum: "62.25.109.197/32"
    quantum_alt: "212.137.36.230/32"
    ark-nps-hmcts-ttp1: "195.59.75.0/24"
    ark-nps-hmcts-ttp2: "194.33.192.0/25"
    ark-nps-hmcts-ttp3: "194.33.193.0/25"
    ark-nps-hmcts-ttp4: "194.33.196.0/25"
    ark-nps-hmcts-ttp5: "194.33.197.0/25"
    dxc_webproxy1: "195.92.38.20/32"
    dxc_webproxy2: "195.92.38.21/32"
    dxc_webproxy3: "195.92.38.22/32"
    dxc_webproxy4: "195.92.38.23/32"

generic-prometheus-alerts:
  targetApplication: dps-monitor
