# Values here are the same across all environments
generic-service:
  nameOverride: dps-monitor

  image:
    repository: quay.io/hmpps/dps-monitor
    tag: app_version # override at deployment time
    port: 3030

  ingress:
    enabled: true
    tlsSecretName: dps-monitor-cert

  livenessProbe:
    httpGet:
      path: /health
      port: 3030
    initialDelaySeconds: 90
    periodSeconds: 30
    timeoutSeconds: 20

  readinessProbe:
    httpGet:
      path: /health
      port: 3030
    initialDelaySeconds: 90
    periodSeconds: 30
    timeoutSeconds: 20

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]
  namespace_secrets:
    dps-monitor:
      CIRCLE_CI_TOKEN: "CIRCLE_CI_TOKEN"

  allowlist:
    groups:
      - internal
      - prisons

generic-prometheus-alerts:
  targetApplication: dps-monitor
