module Config
  PROJECTS = [
    {
      name: 'hmpps-auth',
      versionPath: '/info',
      prodUrl: 'https://sign-in.hmpps.service.justice.gov.uk/auth',
      preprodUrl: 'https://sign-in-preprod.hmpps.service.justice.gov.uk/auth',
      devUrl: 'https://sign-in-dev.hmpps.service.justice.gov.uk/auth',
      title: 'HMPPS Auth',
    },
    {
      name: 'prison-api',
      versionPath: '/info',
      prodUrl: 'https://api.prison.service.justice.gov.uk',
      preprodUrl: 'https://api-preprod.prison.service.justice.gov.uk',
      devUrl: 'https://api-dev.prison.service.justice.gov.uk',
      title: 'Prison API',
      teams: ['syscon'],
    },
    {
      name: 'hmpps-restricted-patients',
      prodUrl: 'https://manage-restricted-patients.hmpps.service.justice.gov.uk',
      preprodUrl: 'https://manage-restricted-patients-preprod.hmpps.service.justice.gov.uk',
      devUrl: 'https://manage-restricted-patients-dev.hmpps.service.justice.gov.uk',
      title: 'HMPPS Restricted Patients',
    },
    {
      name: 'hmpps-restricted-patients-api',
      versionPath: '/info',
      prodUrl: 'https://restricted-patients-api.hmpps.service.justice.gov.uk',
      preprodUrl: 'https://restricted-patients-api-preprod.hmpps.service.justice.gov.uk',
      devUrl: 'https://restricted-patients-api-dev.hmpps.service.justice.gov.uk',
      title: 'HMPPS Restricted Patients API',
    },
    {
      name: 'manage-key-workers',
      prodUrl: 'https://manage-key-workers.service.justice.gov.uk',
      preprodUrl: 'https://preprod.manage-key-workers.service.justice.gov.uk',
      devUrl: 'https://dev.manage-key-workers.service.justice.gov.uk',
      title: 'Key-worker UI',
    },
    {
      name: 'keyworker-api',
      versionPath: '/info',
      prodUrl: 'https://keyworker-api.prison.service.justice.gov.uk',
      preprodUrl: 'https://keyworker-api-preprod.prison.service.justice.gov.uk',
      devUrl: 'https://keyworker-api-dev.prison.service.justice.gov.uk',
      title: 'Keyworker API',
    },
    {
      name: 'dps-core',
      repo: 'digital-prison-services',
      prodUrl: 'https://digital.prison.service.justice.gov.uk',
      preprodUrl: 'https://digital-preprod.prison.service.justice.gov.uk',
      devUrl: 'https://digital-dev.prison.service.justice.gov.uk',
      title: 'DPS Core',
    },
    {
      name: 'whereabouts-api',
      versionPath: '/info',
      prodUrl: 'https://whereabouts-api.service.justice.gov.uk',
      preprodUrl: 'https://whereabouts-api-preprod.service.justice.gov.uk',
      devUrl: 'https://whereabouts-api-dev.service.justice.gov.uk',
      title: 'Whereabouts Api',
    },
    {
      name: 'manage-soc-cases',
      prodUrl: 'https://manage-soc-cases.hmpps.service.justice.gov.uk',
      preprodUrl: 'https://manage-soc-cases-preprod.hmpps.service.justice.gov.uk',
      devUrl: 'https://manage-soc-cases-dev.hmpps.service.justice.gov.uk',
      title: 'Manage SOC Cases',
      teams: ['mase'],
    },
    {
      name: 'offender-case-notes',
      versionPath: '/info',
      prodUrl: 'https://offender-case-notes.service.justice.gov.uk',
      preprodUrl: 'https://preprod.offender-case-notes.service.justice.gov.uk',
      devUrl: 'https://dev.offender-case-notes.service.justice.gov.uk',
      title: 'Offender Case Notes',
    },
    {
      name: 'offender-categorisation',
      healthPath: '',
      prodUrl: 'https://health-kick.prison.service.justice.gov.uk/https/offender-categorisation.service.justice.gov.uk',
      preprodUrl: 'https://health-kick.prison.service.justice.gov.uk/https/preprod.offender-categorisation.service.justice.gov.uk',
      devUrl: 'https://dev.offender-categorisation.service.justice.gov.uk',
      title: 'Offender Categorisation',
      teams: ['mase'],
    },
    {
      name: 'check-my-diary',
      prodUrl: 'https://checkmydiary.service.justice.gov.uk',
      preprodUrl: 'https://check-my-diary-preprod.prison.service.justice.gov.uk',
      devUrl: 'https://check-my-diary-dev.prison.service.justice.gov.uk',
      title: 'Check My Diary',
    },
    {
      name: 'prison-offender-events',
      versionPath: '/info',
      prodUrl: 'https://offender-events.prison.service.justice.gov.uk',
      preprodUrl: 'https://offender-events-preprod.prison.service.justice.gov.uk',
      devUrl: 'https://offender-events-dev.prison.service.justice.gov.uk',
      title: 'Prison Offender Events',
      teams: ['syscon'],
    },
    {
      name: 'offender-events-ui',
      versionPath: '/info',
      devUrl: 'https://offender-events-ui-dev.prison.service.justice.gov.uk',
      title: 'Offender Events UI',
      teams: ['syscon'],
    },
    {
      name: 'prisoner-offender-search',
      versionPath: '/info',
      prodUrl: 'https://prisoner-offender-search.prison.service.justice.gov.uk',
      preprodUrl: 'https://prisoner-offender-search-preprod.prison.service.justice.gov.uk',
      devUrl: 'https://prisoner-offender-search-dev.prison.service.justice.gov.uk',
      title: 'Prisoner Offender Search',
      teams: ['syscon'],
    },
    {
      name: 'licences',
      prodUrl: 'https://licences.prison.service.justice.gov.uk',
      preprodUrl: 'https://licences-preprod.prison.service.justice.gov.uk',
      devUrl: 'https://licences-dev.prison.service.justice.gov.uk',
      title: 'Licences',
    },
    {
       name: 'prison-to-probation-update',
       versionPath: '/info',
       prodUrl: 'https://prison-to-probation-update.prison.service.justice.gov.uk',
       preprodUrl: 'https://prison-to-probation-update-preprod.prison.service.justice.gov.uk',
       devUrl: 'https://prison-to-probation-update-dev.prison.service.justice.gov.uk',
       title: 'Prison to Probation Update',
     },
    {
      name: 'pathfinder',
      prodUrl: 'https://health-kick.prison.service.justice.gov.uk/https/pathfinder.service.justice.gov.uk',
      preprodUrl: 'https://health-kick.prison.service.justice.gov.uk/https/preprod.pathfinder.service.justice.gov.uk',
      devUrl: 'https://dev.pathfinder.service.justice.gov.uk',
      title: 'Pathfinder',
      teams: ['mase'],
    },
    {
      name: 'use-of-force',
      prodUrl: 'https://use-of-force.service.justice.gov.uk',
      preprodUrl: 'https://preprod.use-of-force.service.justice.gov.uk',
      devUrl: 'https://dev.use-of-force.service.justice.gov.uk',
      title: 'Use of Force',
    },
    {
      name: 'token-verification-api',
      versionPath: '/info',
      prodUrl: 'https://token-verification-api.prison.service.justice.gov.uk',
      preprodUrl: 'https://token-verification-api-preprod.prison.service.justice.gov.uk',
      devUrl: 'https://token-verification-api-dev.prison.service.justice.gov.uk',
      title: 'Token Verification api',
    },
    {
      name: 'dps-data-compliance',
      versionPath: '/info',
      prodUrl: 'https://prison-data-compliance.prison.service.justice.gov.uk',
      preprodUrl: 'https://prison-data-compliance-preprod.prison.service.justice.gov.uk',
      devUrl: 'https://prison-data-compliance-dev.prison.service.justice.gov.uk',
      title: 'Data Compliance',
    },
    {
      name: 'case-notes-to-probation',
      versionPath: '/info',
      prodUrl: 'https://health-kick.prison.service.justice.gov.uk/https/case-notes-to-probation.prison.service.justice.gov.uk',
      preprodUrl: 'https://health-kick.prison.service.justice.gov.uk/https/case-notes-to-probation-preprod.prison.service.justice.gov.uk',
      devUrl: 'https://case-notes-to-probation-dev.prison.service.justice.gov.uk',
      title: 'Case Notes to Probation',
    },
    {
      name: 'probation-teams',
      versionPath: '/info',
      prodUrl: 'https://probation-teams.prison.service.justice.gov.uk',
      preprodUrl: 'https://probation-teams-preprod.prison.service.justice.gov.uk',
      devUrl: 'https://probation-teams-dev.prison.service.justice.gov.uk',
      title: 'Probation Teams',
    },
    {
      name: 'pathfinder-api',
      versionPath: '/info',
      prodUrl: 'https://api.pathfinder.service.justice.gov.uk',
      preprodUrl: 'https://preprod-api.pathfinder.service.justice.gov.uk',
      devUrl: 'https://dev-api.pathfinder.service.justice.gov.uk',
      title: 'Pathfinder API',
      teams: ['mase'],
    },
    {
      name: 'prison-services-feedback-and-support',
      prodUrl: 'https://support.hmpps.service.justice.gov.uk',
      preprodUrl: 'https://support-preprod.hmpps.service.justice.gov.uk',
      devUrl: 'https://support-dev.hmpps.service.justice.gov.uk',
      title: 'Prison Services Feedback and Support',
    },
    {
      name: 'community-api',
      versionPath: '/info',
      prodUrl: 'https://health-kick.prison.service.justice.gov.uk/https/community-api.probation.service.justice.gov.uk',
      preprodUrl: 'https://health-kick.prison.service.justice.gov.uk/https/community-api.pre-prod.delius.probation.hmpps.dsd.io',
      stagingUrl: 'https://community-api.stage.probation.service.justice.gov.uk',
      devUrl: 'https://community-api.test.probation.service.justice.gov.uk',
      title: 'Community API',
    },
    {
      name: 'probation-offender-search-indexer',
      versionPath: '/info',
      prodUrl: 'https://probation-search-indexer.hmpps.service.justice.gov.uk',
      preprodUrl: 'https://probation-search-indexer-preprod.hmpps.service.justice.gov.uk',
      stagingUrl: 'https://probation-search-indexer-staging.hmpps.service.justice.gov.uk',
      devUrl: 'https://probation-search-indexer-dev.hmpps.service.justice.gov.uk',
      title: 'Probation Search Indexer',
    },
    {
      name: 'probation-offender-search',
      versionPath: '/info',
      prodUrl: 'https://probation-offender-search.hmpps.service.justice.gov.uk',
      preprodUrl: 'https://probation-offender-search-preprod.hmpps.service.justice.gov.uk',
      stagingUrl: 'https://probation-offender-search-staging.hmpps.service.justice.gov.uk',
      devUrl: 'https://probation-offender-search-dev.hmpps.service.justice.gov.uk',
      title: 'Probation Offender Search',
    },
    {
      name: 'probation-offender-events',
      versionPath: '/info',
      prodUrl: 'https://probation-offender-events.hmpps.service.justice.gov.uk',
      preprodUrl: 'https://probation-offender-events-preprod.hmpps.service.justice.gov.uk',
      stagingUrl: 'https://probation-offender-events-staging.hmpps.service.justice.gov.uk',
      devUrl: 'https://probation-offender-events-dev.hmpps.service.justice.gov.uk',
      title: 'Probation Offender Events',
    },
    {
      name: 'pcms',
      repo: 'hmpps-prisoner-communication-monitoring',
      prodUrl: 'https://pcms.prison.service.justice.gov.uk',
      preprodUrl: 'https://pcms-qa.prison.service.justice.gov.uk',
      devUrl: 'https://pcms-dev.prison.service.justice.gov.uk',
      title: 'PCMS',
      teams: ['mase'],
    },
    {
      name: 'pcms-api',
      versionPath: '/info',
      repo: 'hmpps-prisoner-communication-monitoring-api',
      prodUrl: 'https://pcms-api.prison.service.justice.gov.uk',
      preprodUrl: 'https://pcms-api-qa.prison.service.justice.gov.uk',
      devUrl: 'https://pcms-api-dev.prison.service.justice.gov.uk',
      title: 'PCMS API',
      teams: ['mase'],
    },
    {
      name: 'hmpps-manage-users',
      prodUrl: 'https://manage-users.hmpps.service.justice.gov.uk',
      preprodUrl: 'https://manage-users-preprod.hmpps.service.justice.gov.uk',
      devUrl: 'https://manage-users-dev.hmpps.service.justice.gov.uk',
      title: 'HMPPS User Manager',
    },
    {
      name: 'hmpps-template-kotlin',
      versionPath: '/info',
      devUrl: 'https://hmpps-template-kotlin-dev.hmpps.service.justice.gov.uk',
      title: 'Template kotlin project',
    },
    {
      name: 'manage-intelligence',
      devUrl: 'https://manage-intelligence-dev.prison.service.justice.gov.uk',
      title: 'Manage Intelligence',
      teams: ['mase'],
    },
    {
      name: 'manage-intelligence-api',
      versionPath: '/info',
      devUrl: 'https://manage-intelligence-api-dev.prison.service.justice.gov.uk',
      title: 'Manage Intelligence API',
      teams: ['mase'],
    },
    {
      name: 'hmpps-submit-information-report',
      devUrl: 'https://submit-information-report-dev.hmpps.service.justice.gov.uk',
      title: 'HMPPS Submit Information Report',
      teams: ['mase'],
    },
    {
      name: 'calculate-journey-variable-payments',
      versionPath: '/info',
      prodUrl: 'https://calculate-journey-variable-payments.hmpps.service.justice.gov.uk',
      preprodUrl: 'https://calculate-journey-variable-payments-preprod.apps.live-1.cloud-platform.service.justice.gov.uk',
      devUrl: 'https://calculate-journey-variable-payments-dev.apps.live-1.cloud-platform.service.justice.gov.uk',
      title: 'Calculate Journey Variable Payments',
      teams: ['mase'],
    },
    {
      name: 'hmpps-book-secure-move-frontend',
      healthPath: '/healthcheck',
      prodUrl: 'https://bookasecuremove.service.justice.gov.uk',
      preprodUrl: 'https://hmpps-book-secure-move-frontend-preprod.apps.live-1.cloud-platform.service.justice.gov.uk',
      devUrl: 'https://hmpps-book-secure-move-frontend-staging.apps.live-1.cloud-platform.service.justice.gov.uk',
      title: 'HMPPS Book A Secure Move',
      teams: ['mase'],
    },
    {
      name: 'hmpps-book-secure-move-api',
      prodUrl: 'https://api.bookasecuremove.service.justice.gov.uk',
      preprodUrl: 'https://hmpps-book-secure-move-api-preprod.apps.live-1.cloud-platform.service.justice.gov.uk',
      devUrl: 'https://hmpps-book-secure-move-api-staging.apps.live-1.cloud-platform.service.justice.gov.uk',
      title: 'HMPPS Book A Secure Move API',
      teams: ['mase'],
    },
    {
      name: 'nomis-user-roles-api',
      versionPath: '/info',
      prodUrl: 'https://nomis-user.aks-live-1.studio-hosting.service.justice.gov.uk',
      preprodUrl: 'https://nomis-user-pp.aks-live-1.studio-hosting.service.justice.gov.uk',
      stagingUrl: 'https://nomis-user-stage.aks-dev-1.studio-hosting.service.justice.gov.uk',
      devUrl: 'https://nomis-user-dev.aks-dev-1.studio-hosting.service.justice.gov.uk',
      title: 'NOMIS User Roles API',
    },
    {
      name: 'hmpps-nomis-prisoner-api',
      versionPath: '/info',
      prodUrl: 'https://nomis-prisoner.aks-live-1.studio-hosting.service.justice.gov.uk',
      preprodUrl: 'https://nomis-prsner-pp.aks-live-1.studio-hosting.service.justice.gov.uk',
      devUrl: 'https://nomis-prsner-dev.aks-dev-1.studio-hosting.service.justice.gov.uk',
      title: 'NOMIS Prisoner API',
      teams: ['syscon'],
    },
    {
      name: 'court-register',
      versionPath: '/info',
      prodUrl: 'https://court-register.hmpps.service.justice.gov.uk',
      preprodUrl: 'https://court-register-preprod.hmpps.service.justice.gov.uk',
      devUrl: 'https://court-register-dev.hmpps.service.justice.gov.uk',
      title: 'Court Register',
    },
    {
      name: 'prison-register',
      versionPath: '/info',
      prodUrl: 'https://prison-register.hmpps.service.justice.gov.uk',
      preprodUrl: 'https://prison-register-preprod.hmpps.service.justice.gov.uk',
      devUrl: 'https://prison-register-dev.hmpps.service.justice.gov.uk',
      title: 'Prison Register',
    },
    {
      name: 'hmpps-book-video-link',
      prodUrl: 'https://book-video-link.prison.service.justice.gov.uk',
      preprodUrl: 'https://book-video-link-preprod.prison.service.justice.gov.uk',
      devUrl: 'https://book-video-link-dev.prison.service.justice.gov.uk',
      title: 'Book a video link',
    },
    {
      name: 'hmpps-audit-api',
      versionPath: '/info',
      prodUrl: 'https://audit-api.hmpps.service.justice.gov.uk',
      preprodUrl: 'https://audit-api-preprod.hmpps.service.justice.gov.uk',
      devUrl: 'https://audit-api-dev.hmpps.service.justice.gov.uk',
      title: 'HMPPS Audit API',
    },
    {
      name: 'hmpps-registers',
      prodUrl: 'https://registers.hmpps.service.justice.gov.uk',
      preprodUrl: 'https://registers-preprod.hmpps.service.justice.gov.uk',
      devUrl: 'https://registers-dev.hmpps.service.justice.gov.uk',
      title: 'HMPPS Registers UI',
    },
    {
      name: 'hmpps-registers-to-delius-update',
      versionPath: '/info',
      prodUrl: 'https://registers-to-delius-update.hmpps.service.justice.gov.uk',
      preprodUrl: 'https://registers-to-delius-update-preprod.hmpps.service.justice.gov.uk',
      devUrl: 'https://registers-to-delius-update-dev.hmpps.service.justice.gov.uk',
      title: 'HMPPS Registers to Delius Update',
    },
    {
      name: 'hmpps-registers-to-nomis-update',
      versionPath: '/info',
      prodUrl: 'https://registers-to-nomis-update.hmpps.service.justice.gov.uk',
      preprodUrl: 'https://registers-to-nomis-update-preprod.hmpps.service.justice.gov.uk',
      devUrl: 'https://registers-to-nomis-update-dev.hmpps.service.justice.gov.uk',
      title: 'HMPPS Registers to Nomis Update',
      teams: ['syscon'],
    },
    {
      name: 'hmpps-welcome-people-into-prison-api',
      versionPath: '/info',
      prodUrl: 'https://welcome-api.prison.service.justice.gov.uk',
      preprodUrl: 'https://welcome-api-preprod.prison.service.justice.gov.uk',
      devUrl: 'https://welcome-api-dev.prison.service.justice.gov.uk',
      title: 'HMPPS Welcome to Prison API',
    },
    {
      name: 'hmpps-welcome-people-into-prison-ui',
      prodUrl: 'https://welcome.prison.service.justice.gov.uk',
      preprodUrl: 'https://welcome-preprod.prison.service.justice.gov.uk',
      devUrl: 'https://welcome-dev.prison.service.justice.gov.uk',
      title: 'HMPPS Welcome to Prison UI',
    },
    {
      name: 'manage-soc-cases-api',
      versionPath: '/info',
      prodUrl: 'https://manage-soc-cases-api.hmpps.service.justice.gov.uk',
      preprodUrl: 'https://manage-soc-cases-api-preprod.hmpps.service.justice.gov.uk',
      devUrl: 'https://manage-soc-cases-api-dev.hmpps.service.justice.gov.uk',
      title: 'Manage SOC Cases API',
      teams: ['mase'],
    },
    {
      name: 'hmpps-manage-adjudications',
      prodUrl: 'https://manage-adjudications.hmpps.service.justice.gov.uk',
      preprodUrl: 'https://manage-adjudications-preprod.hmpps.service.justice.gov.uk',
      devUrl: 'https://manage-adjudications-dev.hmpps.service.justice.gov.uk',
      title: 'HMPPS Manage Adjudications',
    },
    {
      name: 'hmpps-manage-adjudications-api',
      versionPath: '/info',
      prodUrl: 'https://restricted-patients-api.hmpps.service.justice.gov.uk',
      preprodUrl: 'https://restricted-patients-api.hmpps.service.justice.gov.uk',
      devUrl: 'https://restricted-patients-api.hmpps.service.justice.gov.uk',
      title: 'HMPPS Adjudications API',
    },
    {
      name: 'hmpps-manage-users-api',
      versionPath: '/info',
      prodUrl: 'https://manage-users-api.hmpps.service.justice.gov.uk',
      preprodUrl: 'https://manage-users-api-preprod.hmpps.service.justice.gov.uk',
      devUrl: 'https://manage-users-api-dev.hmpps.service.justice.gov.uk',
      title: 'HMPPS Manage Users API',
    },
    {
      name: 'create-and-vary-a-licence-api',
      versionPath: '/info',
      preprodUrl: 'https://create-and-vary-a-licence-api-preprod.hmpps.service.justice.gov.uk',
      devUrl: 'https://create-and-vary-a-licence-api-dev.hmpps.service.justice.gov.uk',
      title: 'Create and Vary a Licence API',
    },
    {
      name: 'create-and-vary-a-licence',
      preprodUrl: 'https://create-and-vary-a-licence-preprod.hmpps.service.justice.gov.uk',
      devUrl: 'https://create-and-vary-a-licence-dev.hmpps.service.justice.gov.uk',
      title: 'Create and Vary a Licence',
    },
    {
      name: 'calculate-release-dates-api',
      versionPath: '/info',
      prodUrl: 'https://calculate-release-dates-api.hmpps.service.justice.gov.uk',
      preprodUrl: 'https://calculate-release-dates-api-preprod.hmpps.service.justice.gov.uk',
      devUrl: 'https://calculate-release-dates-api-dev.hmpps.service.justice.gov.uk',
      title: 'Calculate Release Dates API',
    },
    {
      name: 'calculate-release-dates',
      prodUrl: 'https://calculate-release-dates.hmpps.service.justice.gov.uk',
      preprodUrl: 'https://calculate-release-dates-preprod.hmpps.service.justice.gov.uk',
      devUrl: 'https://calculate-release-dates-dev.hmpps.service.justice.gov.uk',
      title: 'Calculate Release Dates',
    },
    {
      name: 'book-a-prison-visit-staff-ui',
      prodUrl: 'https://manage-a-prison-visit.hmpps.service.justice.gov.uk',
      preprodUrl: 'https://manage-a-prison-visit-preprod.hmpps.service.justice.gov.uk',
      devUrl: 'https://manage-a-prison-visit-dev.hmpps.service.justice.gov.uk',
      title: 'VSiP Staff UI',
    },
    {
      name: 'visit-scheduler',
      versionPath: '/info',
      prodUrl: 'https://visit-scheduler.hmpps.service.justice.gov.uk',
      preprodUrl: 'https://visit-scheduler-preprod.hmpps.service.justice.gov.uk',
      devUrl: 'https://visit-scheduler-dev.hmpps.service.justice.gov.uk',
      title: 'Visit Scheduler API',
    },
    {
      name: 'hmpps-prisoner-to-nomis-update',
      versionPath: '/info',
      prodUrl: 'https://prisoner-to-nomis-update.hmpps.service.justice.gov.uk',
      preprodUrl: 'https://prisoner-to-nomis-update-preprod.hmpps.service.justice.gov.uk',
      devUrl: 'https://prisoner-to-nomis-update-dev.hmpps.service.justice.gov.uk',
      title: 'HMPPS Prisoner to NOMIS Update',
      teams: ['syscon'],
    },
    {
      name: 'hmpps-prisoner-from-nomis-migration',
      versionPath: '/info',
      prodUrl: 'https://prisoner-nomis-migration.hmpps.service.justice.gov.uk',
      preprodUrl: 'https://prisoner-nomis-migration-preprod.hmpps.service.justice.gov.uk',
      devUrl: 'https://prisoner-nomis-migration-dev.hmpps.service.justice.gov.uk',
      title: 'HMPPS Prisoner from NOMIS Migration',
      teams: ['syscon'],
    },
    {
      name: 'hmpps-nomis-visits-mapping-service',
      versionPath: '/info',
      prodUrl: 'https://nomis-visits-mapping.hmpps.service.justice.gov.uk',
      preprodUrl: 'https://nomis-visits-mapping-preprod.hmpps.service.justice.gov.uk',
      devUrl: 'https://nomis-visits-mapping-dev.hmpps.service.justice.gov.uk',
      title: 'HMPPS NOMIS Visits Mapping',
      teams: ['syscon']
    },
    {
      name: 'hmpps-incentives-ui',
      prodUrl: 'https://incentives-ui.hmpps.service.justice.gov.uk',
      preprodUrl: 'https://incentives-ui-preprod.hmpps.service.justice.gov.uk',
      devUrl: 'https://incentives-ui-dev.hmpps.service.justice.gov.uk',
      title: 'Incentives UI',
    },
    {
      name: 'hmpps-incentives-api',
      versionPath: '/info',
      prodUrl: 'https://incentives-api.hmpps.service.justice.gov.uk',
      preprodUrl: 'https://incentives-api-preprod.hmpps.service.justice.gov.uk',
      devUrl: 'https://incentives-api-dev.hmpps.service.justice.gov.uk',
      title: 'Incentives API',
    },
    {
      name: 'send-legal-mail-to-prisons-api',
      versionPath: '/info',
      prodUrl: 'https://send-legal-mail-api.prison.service.justice.gov.uk',
      preprodUrl: 'https://send-legal-mail-api-preprod.prison.service.justice.gov.uk',
      devUrl: 'https://send-legal-mail-api-dev.prison.service.justice.gov.uk',
      title: 'Send Legal Mail To Prisons API',
    },
    {
      name: 'send-legal-mail-to-prisons',
      prodUrl: 'https://send-legal-mail.prison.service.justice.gov.uk',
      preprodUrl: 'https://send-legal-mail-preprod.prison.service.justice.gov.uk',
      devUrl: 'https://send-legal-mail-dev.prison.service.justice.gov.uk',
      title: 'Send Legal Mail To Prisons',
    },
  ]

  TEAMS = [
    { name: 'mase', title: 'Manage a Secure Area (MASE)' },
    { name: 'syscon', title: 'Syscon Projects' }
  ]
  TEAMS_TITLES = TEAMS.map { |team| [team[:name], team[:title]] }.to_h

  TEAM_PROJECTS = TEAMS.map { |team|
    [team[:name], PROJECTS.filter { |project| project[:teams]&.include? team[:name] }]
  }.to_h
end
