apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  CIRCLE_CI_TOKEN: {{ .Values.secrets.CIRCLE_CI_TOKEN | b64enc | quote }}
