# Environment specific values, override helm_deploy/dps-monitor/values.yaml
generic-service:
  replicaCount: 2

  ingress:
    host: dps-monitor.prison.service.justice.gov.uk
    contextColour: green


# CloudPlatform AlertManager receiver to route prometheus alerts to slack
generic-prometheus-alerts:
  alertSeverity: hmpps_tech
