# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

image:
  repository: docker.io/mojdigitalstudio/dps-monitor
  tag: latest
  pullPolicy: IfNotPresent
  port: 3030

ingress:
  enabled: true
  enable_whitelist: false
  host: dps-monitor.prison.service.justice.gov.uk
  cert_secret: dps-monitor-cert
  path: /
